name: CataMines
version: '${project.version}'
main: de.c4t4lysm.catamines.CataMines
api-version: 1.13
authors: [ CatalysmRL (C4t4lysm) ]
description: §6[§bCata§aMines§6] §7Mines plugin
depend: [ WorldEdit ]
softdepend: [ PlaceholderAPI ]

commands:
  catamines:
    description: §7Contains every mine manipulation command.
    usage: §b/<command>
    aliases: [ "cm" , "cmines", "cmine", "mines", "mine" ]

permissions:
  catamines.*:
    description: §7Grants access to every command.
    default: op
    children:
      catamines.help: true
      catamines.create: true
      catamines.delete: true
      catamines.gui: true
      catamines.list: true
      catamines.info: true
      catamines.set: true
      catamines.unset: true
      catamines.resetmode: true
      catamines.setdelay: true
      catamines.resetpercentage: true
      catamines.flag: true
      catamines.reset: true
      catamines.setteleport: true
      catamines.teleport: true
      catamines.start: true
      catamines.stop: true
      catamines.starttasks: true
      catamines.stoptasks: true
      catamines.reload: true
      catamines.break: true
  catamines.help:
    description: §7Lets you list all mine commands.
    default: op
  catamines.create:
    description: §7Lets you create a mine.
    default: op
  catamines.delete:
    description: §7Lets you delete a mine.
    default: op
  catamines.gui:
    description: §7Lets you open the gui
    default: op
  catamines.list:
    description: §7Lets you list all mines.
    default: op
  catamines.info:
    description: §7Lets you display info of a mine.
    default: op
  catamines.set:
    description: §7Lets you set the blocks of a mine.
    default: op
  catamines.unset:
    description: §7Lets you unset the blocks of a mine.
    default: op
  catamines.resetmode:
    description: §7Lets you set the reset mode of a mine.
    default: op
  catamines.setdelay:
    description: §7Lets you set the reset delay of a mine.
    default: op
  catamines.resetpercentage:
    description: §7Lets you set the reset percentage of a mine.
    default: op
  catamines.flag:
    description: §7Lets you configure every flag of a mine.
    default: op
  catamines.reset:
    description: §7Lets you manually reset a mine
    default: op
  catamines.setteleport:
    description: §7Lets you set a teleport location of a mine.
    default: op
  catamines.teleport:
    description: §7Lets you teleport to a mine.
    default: op
  catamines.start:
    description: §7Lets you start a mine.
    default: op
  catamines.stop:
    description: §7Lets you stop a mine.
    default: op
  catamines.starttasks:
    description: §7Starts all mine tasks
    default: op
  catamines.stoptasks:
    description: §7Stops all mine tasks
    default: op
  catamines.reload:
    description: §7Lets you reload the plugin.
    default: op
  catamines.break:
    description: §7Lets you bypass min. mine efficiency lvl to break blocks.
    default: op